version: 0.2

# env:
#   parameter-store:
#      DOCKERHUB_USERNAME: "/pay-cd/concourse/pipelines/main/docker-username"
#      DOCKERHUB_PASSWORD: "/pay-cd/concourse/pipelines/main/docker-password"
phases:
  install:
    commands:
      - yum update -y
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      # - echo Logging in to Docker Hub...
      # - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - echo Building image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - >-
        docker tag $IMAGE_REPO_NAME:$IMAGE_TAG
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - >-
        docker tag $IMAGE_REPO_NAME:$IMAGE_TAG
        governmentdigitalservice/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing $IMAGE_REPO_NAME:$IMAGE_TAG to ECR...
      - >-
        docker push
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      # - echo Pushing $IMAGE_REPO_NAME:$IMAGE_TAG to Docker Hub...
      # - >-
      #   docker push
      #   governmentdigitalservice/$IMAGE_REPO_NAME:$IMAGE_TAG
